// ===== AUTH CONFIG =====

// Access token
const ACCESS_TOKEN_EXPIRE = "15m"; // JWT expire
const ACCESS_TOKEN_COOKIE_MAX_AGE = 60 * 15; // 15 phút (giây)

// Refresh token
const REFRESH_TOKEN_EXPIRE_DAYS = 7;
const REFRESH_TOKEN_EXPIRE = `${REFRESH_TOKEN_EXPIRE_DAYS}d`; // JWT expire
const REFRESH_TOKEN_COOKIE_MAX_AGE =
  60 * 60 * 24 * REFRESH_TOKEN_EXPIRE_DAYS; // 7 ngày (giây)

export {
  ACCESS_TOKEN_EXPIRE,
  ACCESS_TOKEN_COOKIE_MAX_AGE,
  REFRESH_TOKEN_EXPIRE,
  REFRESH_TOKEN_EXPIRE_DAYS,
  REFRESH_TOKEN_COOKIE_MAX_AGE,
};
