// ===== AUTH CONFIG =====
const ACCESS_TOKEN_EXPIRE = "1m";
const ACCESS_TOKEN_COOKIE_MAX_AGE = 60 * 1; // 15 phút (giây)
const REFRESH_TOKEN_EXPIRE_DAYS = 7;
const REFRESH_TOKEN_COOKIE_MAX_AGE = 60 * 60 * 24 * REFRESH_TOKEN_EXPIRE_DAYS;

export {
  ACCESS_TOKEN_EXPIRE,
  ACCESS_TOKEN_COOKIE_MAX_AGE,
  REFRESH_TOKEN_EXPIRE_DAYS,
  REFRESH_TOKEN_COOKIE_MAX_AGE
}